# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0002_auto_20171210_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='original_data',
            name='securities',
        ),
    ]
