# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0003_remove_original_data_securities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original_data',
            name='Cpb',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='original_data',
            name='Cpc',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='original_data',
            name='Market',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='original_data',
            name='Wb',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='original_data',
            name='Wc',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='original_data',
            name='year',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
