# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0004_auto_20171210_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original_data',
            name='Wa',
            field=models.FloatField(blank=True, default=0.43),
        ),
        migrations.AlterField(
            model_name='original_data',
            name='Wb',
            field=models.FloatField(blank=True, default=0.3),
        ),
        migrations.AlterField(
            model_name='original_data',
            name='Wc',
            field=models.FloatField(blank=True, default=0.27),
        ),
    ]
