# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-16 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0005_auto_20171210_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='original_data',
            options={'ordering': ['year'], 'verbose_name': 'Данні за конретний рік', 'verbose_name_plural': 'Початкові данні'},
        ),
        migrations.AddField(
            model_name='original_data',
            name='probability_rate_profit',
            field=models.FloatField(default=0.9973),
        ),
    ]
