# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-16 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0007_auto_20171216_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additional_data',
            options={'verbose_name': 'допоміжну змінну', 'verbose_name_plural': 'Додаткові данні'},
        ),
    ]
