# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-14 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0009_auto_20171216_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculated_variants',
            old_name='average_profit_for_cp',
            new_name='average_profit_for_cp_a',
        ),
        migrations.RenameField(
            model_name='calculated_variants',
            old_name='realize_profit_bet_portfolio',
            new_name='average_profit_for_cp_b',
        ),
        migrations.RenameField(
            model_name='calculated_variants',
            old_name='sigma',
            new_name='average_profit_for_cp_c',
        ),
        migrations.AddField(
            model_name='calculated_variants',
            name='average_profit_for_market',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calculated_variants',
            name='average_profit_for_portfolio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calculated_variants',
            name='sigma_a',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calculated_variants',
            name='sigma_b',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calculated_variants',
            name='sigma_c',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calculated_variants',
            name='sigma_portfolio',
            field=models.FloatField(default=0),
        ),
    ]
