# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-14 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0011_remove_calculated_variants_average_profit_for_market'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additional_data',
            name='probability_rate_profit',
        ),
        migrations.AddField(
            model_name='additional_data',
            name='x_value_on_diagramm',
            field=models.FloatField(default=0.85),
        ),
    ]
