# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0012_auto_20180114_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='additional_data',
            name='free_risk_cp',
            field=models.FloatField(default=12),
        ),
    ]
