# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0013_additional_data_free_risk_cp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additional_data',
            old_name='x_value_on_diagramm',
            new_name='upper_bound_for_chart',
        ),
    ]
