# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-16 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_remove_results_compliting_task_updateds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tests',
            old_name='question_1',
            new_name='answer_1',
        ),
        migrations.RenameField(
            model_name='tests',
            old_name='question_2',
            new_name='answer_2',
        ),
        migrations.RenameField(
            model_name='tests',
            old_name='question_3',
            new_name='answer_3',
        ),
        migrations.RenameField(
            model_name='tests',
            old_name='question_4',
            new_name='answer_4',
        ),
        migrations.AddField(
            model_name='tests',
            name='question',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
