# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-21 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_auto_20180216_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='hint',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='resolving_hint',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
