# Generated by Django 2.0.2 on 2018-03-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_auto_20180225_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection_definition',
            name='definition_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='connection_definition',
            name='definition_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='connection_definition',
            name='definition_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='connection_definition',
            name='definition_4',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
